name: check-services

on: [push]

jobs:
  check-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["example"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
    - name: test
      run: docker ps -a
